### ISSUE TITLE
segfault on some registration packets

### ISSUE THREAD

**Issue by nshopik** [irontec/sngrep#240]
```
#0  0x00007ffff7dd1775 in vector_iterator_next (it=0x20746361746e6f63, it@entry=0x7fffffffe5d0) at vector.c:342                                                                                                    
#1  0x00007ffff7dd877e in call_flow_draw_arrows (ui=0x2072756f79206e69, ui@entry=0x7ffff7ff7a20 <ui_call_flow>) at curses/ui_call_flow.c:349                                                                       
#2  0x00007ffff7dd88bb in call_flow_draw (ui=0x7ffff7ff7a20 <ui_call_flow>) at curses/ui_call_flow.c:185                                                                                                           
#3  0x00007ffff7dd2498 in ui_wait_for_input () at curses/ui_manager.c:205                                                                                                                                          
#4  0x00007ffff7dc62c9 in main (argc=2, argv=0x7fffffffeaf8) at main.c:397    
```

**Comment by Kaian** [comment]
The problem was related with a big response-text in the messages. The above commit should avoid the crash.

Thanks for the testing data! :+1:
